## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Stream IoT data to an autonomous database using serverless functions"
    stackDescription: "Deploy Oracle Cloud Infrastructure Streaming to support IoT devices data streams uploaded into the cloud at scale."
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - region

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - atp_admin_user
      - atp_admin_password
      - atp_user
      - atp_password
      - ocir_namespace
      - ocir_repo_name
      - ocir_docker_repository
      - ocir_user_name
      - ocir_user_password

    - title: Optional Configuration
      visible: true
      variables:      
      - VCN-CIDR
      - ATPsubnet-CIDR
      - websubnet-CIDR
      - VCNname
      - httpx_ports
      - Shape
      - OsImage
      - ATP_database_cpu_core_count
      - ATP_database_data_storage_size_in_tbs
      - ATP_database_db_name
      - ATP_database_db_version
      - ATP_database_display_name
      - ATP_database_license_model
      - ATP_tde_wallet_zip_file
      - ATP_database_atp_private_endpoint_label
      - ATP_database_freeform_tags
      - ATP_database_defined_tags_value
    
    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      atp_admin_user:
        type: string
        required: true
        visibile: true
        default: "admin"
        title: "ATP admin username."
        description: "ATP admin username."

      atp_admin_password:
        type: password
        required: true
        visibile: true
        title: "ATP Admin Database password"
        description: "ATP Database password for ADMIN user"
        minLength: 12
        maxLength: 30
        pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

      atp_user:
        type: string
        required: true
        visibile: true
        default: "oraapp"
        title: "ATP application username."
        description: "ATP application username."

      atp_password:
        type: password
        required: true
        visibile: true
        title: "ATP App User Database password"
        description: "ATP Database password for Application user"
        minLength: 12
        maxLength: 30
        pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

      ocir_namespace:
        type: string
        required: true
        visibile: true
        title: "OCIR namespace"
        description: "Oracle Cloud Infrastructure Registry namespace (can be the same as your tenancy name)"

      ocir_repo_name:
        type: string
        required: true
        visibile: true
        title: "OCIR repository name"
        description: "Oracle Cloud Infrastructure Registry repository name (for example functions)"

      ocir_docker_repository:
        type: string
        required: true
        visibile: true
        title: "OCIR Docker Repository URL"
        description: "Oracle Cloud Infrastructure Registry Docker Repository URL (for example iad.ocir.io)" 

      ocir_user_name:
        type: string
        required: true
        visibile: true
        title: "OCIR username"
        description: "Oracle Cloud Infrastructure Registry username (your OCI username)" 

      ocir_user_password:
        type: password
        required: true
        visibile: true
        title: "OCIR user password"
        description: "Oracle Cloud Infrastructure Registry user password (your OCI user authtoken)" 

      # Optional Configuration
      VCN-CIDR:
        type: string
        required: false
        default: "10.0.0.0/16"
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        description: "VCN CIDR block where you want to create the solution resources."

      ATPsubnet-CIDR:
        type: string
        required: false
        default: "10.0.2.0/24"
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        description: "Private subnet's CIDR block where you want to place your Private Endpoint for ATP."

      websubnet-CIDR:
        type: string
        required: false
        default: "10.0.1.0/24"
        pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
        description: "Public subnet's CIDR block where you want to place your Flask-based Webserver VM."
      
      VCNname:
        type: string
        required: false
        default: "VCN"
        description: "Name for your VCN where want to create the solution resources."  

      httpx_ports:
        type: string
        required: false
        default: "[80,443]"
        description: "HTTP and HTTPS ports."

      Shape:
        type: oci:core:instanceshape:name
        required: false
        default: "VM.Standard.E2.1"
        description: "Shape of the VM used for Flask-based Webserver VM."
        dependsOn:
          compartmentId: ${compartment_ocid}

      OsImage:
        type: string
        required: false
        default: "Oracle-Linux-7.8-2020.05.26-0"
        description: "OEL image used for Flask-based Webserver VM."

      ATP_database_cpu_core_count:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 1
        description: "ATP Database CPU Core Count"

      ATP_database_data_storage_size_in_tbs:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 1
        description: "ATP Database Data Storage Size in terabytes"

      ATP_database_db_name:
        type: string
        required: false
        default: "atpdb1"
        description: "ATP Database DBNAME"

      ATP_database_db_version:
        type: enum
        required: false
        default: "19c"
        description: "ATP Database Version"
        enum:
          - "19c"

      ATP_database_display_name:
        type: string
        required: false
        default: "ATPDB"
        description: "ATP Database Display Name"

      ATP_database_license_model:
        type: enum
        required: false
        default: "LICENSE_INCLUDED"
        description: "ATP Database License Model"
        enum:
          - "LICENSE_INCLUDED"
          - "BRING_YOUR_OWN_LICENSE"

      ATP_tde_wallet_zip_file:
        type: string
        required: false
        default: "tde_wallet_ATPdb1.zip"
        description: "ATP Database TDE Wallet ZIP File"

      ATP_database_atp_private_endpoint_label:
        type: string
        required: false
        default: "ATPPrivateEndpoint"
        description: "ATP Database Private Endpoint Label"

      ATP_database_freeform_tags:
        type: string
        required: false
        description: "ATP Database Freeform Tags"

      ATP_database_defined_tags_value:
        type: string
        required: false
        description: "ATP Database Defined Tags"

    outputs:
      
      generated_ssh_private_key:
        title: "Generated SSH Private Key"
        displayText: "Generated SSH Private Key"
        type: string
        visible: true
      